name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main  # ou master, depende do nome do teu branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Upload de artefatos
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # aqui vai todo o conteúdo da pasta raiz, incluindo index.html

      - name: Deploy no GitHub Pages
        uses: actions/deploy-pages@v4
